"""add_title_ky_description_ky_to_movies

Revision ID: 1e85d719dd04
Revises: da263e67dd6a
Create Date: 2026-05-22 10:35:38.495173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e85d719dd04'
down_revision: Union[str, None] = 'da263e67dd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title_ky', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('description_ky', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'description_ky')
    op.drop_column('movies', 'title_ky')
    # ### end Alembic commands ###
