"""nullable_user_id_in_history

Revision ID: 31fdefa95221
Revises: 44242a6a992a
Create Date: 2026-05-21 14:23:34.173501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31fdefa95221'
down_revision: Union[str, None] = '44242a6a992a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('play_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('play_history_user_id_fkey', 'play_history', type_='foreignkey')
    op.create_foreign_key(None, 'play_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('view_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('view_history_user_id_fkey', 'view_history', type_='foreignkey')
    op.create_foreign_key(None, 'view_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view_history', type_='foreignkey')
    op.create_foreign_key('view_history_user_id_fkey', 'view_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('view_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'play_history', type_='foreignkey')
    op.create_foreign_key('play_history_user_id_fkey', 'play_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('play_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
