"""add_multilingual_all_models

Revision ID: ad476c813f71
Revises: 1e85d719dd04
Create Date: 2026-05-22 10:58:40.938519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad476c813f71'
down_revision: Union[str, None] = '1e85d719dd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('title_ru', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('title_kk', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('title_ky', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('subtitle_ru', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('subtitle_kk', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('subtitle_ky', sa.String(length=255), nullable=True))
    op.add_column('banners', sa.Column('body_ru', sa.Text(), nullable=True))
    op.add_column('banners', sa.Column('body_kk', sa.Text(), nullable=True))
    op.add_column('banners', sa.Column('body_ky', sa.Text(), nullable=True))
    op.add_column('flight_info', sa.Column('origin_city_ru', sa.String(length=100), nullable=True))
    op.add_column('flight_info', sa.Column('origin_city_kk', sa.String(length=100), nullable=True))
    op.add_column('flight_info', sa.Column('origin_city_ky', sa.String(length=100), nullable=True))
    op.add_column('flight_info', sa.Column('destination_city_ru', sa.String(length=100), nullable=True))
    op.add_column('flight_info', sa.Column('destination_city_kk', sa.String(length=100), nullable=True))
    op.add_column('flight_info', sa.Column('destination_city_ky', sa.String(length=100), nullable=True))
    op.add_column('movie_categories', sa.Column('name_ru', sa.String(length=100), nullable=True))
    op.add_column('movie_categories', sa.Column('name_kk', sa.String(length=100), nullable=True))
    op.add_column('movie_categories', sa.Column('name_ky', sa.String(length=100), nullable=True))
    op.add_column('movie_categories', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('movie_categories', sa.Column('description_kk', sa.Text(), nullable=True))
    op.add_column('movie_categories', sa.Column('description_ky', sa.Text(), nullable=True))
    op.add_column('music', sa.Column('title_ru', sa.String(length=255), nullable=True))
    op.add_column('music', sa.Column('title_kk', sa.String(length=255), nullable=True))
    op.add_column('music', sa.Column('title_ky', sa.String(length=255), nullable=True))
    op.add_column('music', sa.Column('genre_ru', sa.String(length=100), nullable=True))
    op.add_column('music', sa.Column('genre_kk', sa.String(length=100), nullable=True))
    op.add_column('music', sa.Column('genre_ky', sa.String(length=100), nullable=True))
    op.add_column('playlists', sa.Column('name_ru', sa.String(length=255), nullable=True))
    op.add_column('playlists', sa.Column('name_kk', sa.String(length=255), nullable=True))
    op.add_column('playlists', sa.Column('name_ky', sa.String(length=255), nullable=True))
    op.add_column('playlists', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('playlists', sa.Column('description_kk', sa.Text(), nullable=True))
    op.add_column('playlists', sa.Column('description_ky', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'description_ky')
    op.drop_column('playlists', 'description_kk')
    op.drop_column('playlists', 'description_ru')
    op.drop_column('playlists', 'name_ky')
    op.drop_column('playlists', 'name_kk')
    op.drop_column('playlists', 'name_ru')
    op.drop_column('music', 'genre_ky')
    op.drop_column('music', 'genre_kk')
    op.drop_column('music', 'genre_ru')
    op.drop_column('music', 'title_ky')
    op.drop_column('music', 'title_kk')
    op.drop_column('music', 'title_ru')
    op.drop_column('movie_categories', 'description_ky')
    op.drop_column('movie_categories', 'description_kk')
    op.drop_column('movie_categories', 'description_ru')
    op.drop_column('movie_categories', 'name_ky')
    op.drop_column('movie_categories', 'name_kk')
    op.drop_column('movie_categories', 'name_ru')
    op.drop_column('flight_info', 'destination_city_ky')
    op.drop_column('flight_info', 'destination_city_kk')
    op.drop_column('flight_info', 'destination_city_ru')
    op.drop_column('flight_info', 'origin_city_ky')
    op.drop_column('flight_info', 'origin_city_kk')
    op.drop_column('flight_info', 'origin_city_ru')
    op.drop_column('banners', 'body_ky')
    op.drop_column('banners', 'body_kk')
    op.drop_column('banners', 'body_ru')
    op.drop_column('banners', 'subtitle_ky')
    op.drop_column('banners', 'subtitle_kk')
    op.drop_column('banners', 'subtitle_ru')
    op.drop_column('banners', 'title_ky')
    op.drop_column('banners', 'title_kk')
    op.drop_column('banners', 'title_ru')
    # ### end Alembic commands ###
